- name: Setup Database
  hosts: database

  tasks:
    - name: Install Mariadb server
      apt: name=mariadb-server state=present

    - name: Enable mariadb service
      service: name=mariadb enabled=yes state=started

    - name: Install python3 mysql connector
      apt: name=python3-mysqldb state=present

    - name: Set bind-address in my.cnf
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address\s*='
        line: "bind-address = 0.0.0.0"
        state: present
      register: bind_address

    - name: Restart mysql service
      service:
        name: mysql
        state: restarted
      when: bind_address.changed

    - name: Create database user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "*.*:ALL,GRANT"
        host: "{{ remote_host_ip }}"
        state: present

    - name: Create database
      mysql_db:
        name: "nsa"
        state: present
