- name: Setup Database
  hosts: database

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Check if mariadb is installed
      stat: path=/usr/sbin/mysqld
      register: mariadb_installed

    - name: Install Mariadb server
      apt: name=mariadb-server state=present
      when: not mariadb_installed.stat.exists

    - name: Enable mariadb service
      service: name=mariadb enabled=yes state=started

    - name: Install python3 mysql connector
      apt: name=python3-mysqldb state=present
      when: not mariadb_installed.stat.exists

    - name: Set bind-address in my.cnf
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address\s*='
        line: "bind-address = 0.0.0.0"
        state: present
      register: bind_address
      when: not mariadb_installed.stat.exists

    - name: Restart mysql service
      service:
        name: mysql
        state: restarted
      when: bind_address.changed
      when: not mariadb_installed.stat.exists

    - name: Create database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "*.*:ALL,GRANT"
        host: "{{ backend_host }}"
        state: present
      when: not mariadb_installed.stat.exists

    - name: Create database
      mysql_db:
        name: "nsa"
        state: present
      when: not mariadb_installed.stat.exists
